[package]
name = "aoc"
version = "0.1.0"
authors = ["Ryan J. Evans <ryan@overmatch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
parsing = { path = "parsing" }
rayon = "1"
regex = "1"
